#!/bin/bash

source ~/.config/lemonbar/setup

while true; do
    echo "%{l}%{O 2}$(workspace) $(volume) $(music)\
          %{c}$(title)\
          %{r}$(battery) $(network) %{O 2} $(_date) %{O 2} $(_time) $(power)"
    sleep 1s
done |

lemonbar\
    -b\
    -g "x32"\
    -F "#ffffff"\
    -B "#19000000"\
    -f "$PANEL_FONT_FAMILY"\
    -f "$OTHER_ICON_FONT"\
    -f "$ICON_FONT" | bash
